### ISSUE TITLE
CPU mode gives wrong 3D pose results

### ISSUE THREAD

**Issue by handsomeyang** [timctho/VNect-tensorflow#3] opened 2017-11-30 10:25 UTC
```
python demo_tf.py --device=cpu \
		   --demo_type=image \
		   --test_file=test_imgs/yuniko.jpg \
		   --model_file=models/weights/vnect_tf \
		   --plot_2d=True \
		   --plot_3d=True
```

![figure_1](https://user-images.githubusercontent.com/1124230/33426161-de448376-d5fb-11e7-88d4-47b3fc4e8ea7.png)
![figure_2](https://user-images.githubusercontent.com/1124230/33426165-e36cb922-d5fb-11e7-89f4-31634b12e339.png)

**Comment by timctho** [comment] 2017-11-30 15:54
I think it's not related to cpu or gpu, but there's some problem in 3d pose now.

**Comment by larrypm** [comment] 2017-12-04 13:22
Has anyone traced the cause of the error?

**Comment by oguzhankarabulut** [comment] 2017-12-04 13:41
I am taking same results. Has anyone solved this problem ?

**Comment by oguzhankarabulut** [comment] 2017-12-04 14:14
@timctho I think there is some problem in 2d pose results. Joints are not in true localizations.

**Comment by segatecm** [comment] 2017-12-26 09:53
can any one send me the VNect model file? Thanks!

**Comment by HonglianJiang** [comment] 2018-01-20 10:31
@timctho  How can I get the models/weights/vnect_tf file?

**Comment by SuperLee506** [comment] 2018-01-28 20:16
Mabe, it just missed the step of "Kinematic Skeleton Fiting”

**Comment by segatecm** [comment] 2018-01-29 02:31
@SuperLee506 can you tell me more about "Kinematic Skeleton Fiting”? Is it wrote in the paper?

**Comment by oldaltarsauerkraut** [comment] 2018-05-07 10:40
3d pose is also a problem, i test some but cant get a good result, anybody has good idea?

**Comment by cDenius** [comment] 2018-05-15 09:34
there is a mistake in **utils.py** 

in **def extract_3d_joints_from_heatmap** x and y is mixed up (line 80 and 81). it should be 

`coord_2d_x = joints_2d[joint_num][0]
coord_2d_y = joints_2d[joint_num][1]`


After fixing that the 3D plot looks fine (although the axes are messed up)

**Comment by cDenius** [comment] 2018-05-15 16:38
there is a mistake in **utils/utils.py** 

in **def extract_3d_joints_from_heatmap** x and y is mixed up (line 80 and 81). it should be 

```
coord_2d_x = joints_2d[joint_num][0] 
coord_2d_y = joints_2d[joint_num][1]
```


After fixing that the 3D plot looks fine (although the axes are messed up)

**Comment by yukaliu07** [comment] 2018-06-06 03:42
Did you guys use caffe_weights_to_pickle.py to convert the model to vnect.pkl, then run vnect_model.py to produce vnect_tf files? I'm getting a weird 2D pose following this process, but using the original caffe model is fine.

**Comment by powermew** [comment] 2018-06-14 07:02
This is my output from above method.
It is quite different from above result.
In my case, 3D skeleton is also wrongly estimated.
How can I get the good estimation?

![image](https://user-images.githubusercontent.com/29700379/41396538-4300d26c-6fec-11e8-957e-f6c981544261.png)

**Comment by cDenius** [comment] 2018-06-14 09:10
Well not even your 2D pose is correct and it should be working if you checkout the current repository.
Are sure you changed the correct lines of code?

**Comment by powermew** [comment] 2018-06-14 10:42
I had tried this code with these follows.

1) Download weights from the author of paper
2) change weights with using './caffe_weight_to_pickle.py'
3) run '/models/vnect_model.py' to get
```
   vnect_tf.data-00000-of-00001
   vnect_tf.index
   vnect_tf.meta
```
4) change the code
```
   coord_2d_x = joints_2d[joint_num][0] 
   coord_2d_y = joints_2d[joint_num][1]
```
5) run '/demo_tf.py'

If you can share your parameters, could you send it to my e-mail?
 - powermew@hanyang.ac.kr

**Comment by cDenius** [comment] 2018-06-14 14:45
That is weird. If you don't change the two lines of code do you get the same results as the OP?
I get the desired output without doing or changing anything else besides the 5 steps you have described.

**Comment by powermew** [comment] 2018-06-14 15:06
@cDenius
So do you have tensorflow weights without conversion??
Where did you get that weights?
i mean vnect_tf~ files

**Comment by lavage** [comment] 2018-07-02 11:09
The messed up axes can be fixed by switching y_pair and x_pair in draw_limbs_3d in utils.py (lines 112+113):

![correct](https://user-images.githubusercontent.com/39333276/42160885-1de2b160-7df9-11e8-97f5-6d989e92d986.png)

**Comment by zeroHuang0516** [comment] 2018-10-09 08:56
@lavage 
I can reproduce your results by following your procedures, but it seems like the z coordinates of 3d joint points are incorrect.
Have you observed any similar situations?
Thanks.

**Comment by lavage** [comment] 2018-10-09 09:55
@zeroHuang0516 
That is what I meant with the scaling issue, you just defined it a bit better ;). Unless you are having different z coordinate issues than shown in my picture above?

As the overall body composition looks ok, it wouldn't be too difficult to normalize the z coordinates however.

**Closed** 2019-01-09 14:38 UTC
